### ISSUE TITLE
translation of website

### ISSUE THREAD

**Issue by berlintam** [rubycorns/jaa#2]
If would be great to have the site in German as well!

**Comment by BriocheBerlin** [comment]
I18n it is then?

**Comment by berlintam** [comment]
Is that possible with a basic html/css site? I only know it in the context of rails. But if it's possible, sure!

My basic not thought out idea was just a separate page. So `juniorsareawesome.org/de` or something, with the German on it. And then we could have little flags in the corner - super profesh like - that sends you to the German page, or back to the English one. 

wdyt?

**Comment by BriocheBerlin** [comment]
Right, that is probably the simplest solution.

**Comment by sareg0** [comment]
I am in favour of simple at this point. @BriocheBerlin are you taking this on? Do let us know if you need any help; you can ask here or ping us in the slack channel. Many many thanks!

**Comment by BriocheBerlin** [comment]
Yeah, I already have a rough translation but it definitely needs some polishing...

**Comment by berlintam** [comment]
awesome! Did you see that we added a section for seniors & how they can contribute?

**Comment by BriocheBerlin** [comment]
No, I didn't! Great! I'll add that :)

**Comment by berlintam** [comment]
done! woot!
