### ISSUE TITLE
Section for supporters that are not our target group

### ISSUE THREAD

**Issue by sareg0** [rubycorns/jaa#4]
Perhaps they are people with jobs to offer, or devs that are past the junior stage. How can they get involved? Where do they fit in our totally awesome humble group?

Ideas can go here, but we could also add a quick section to the website to address this, and point them somewhere to get in touch with any ideas as we think this all through.

**Comment by berlintam** [comment]
I think that this was accomplished on the weekend w/ the link to the 'new issue' section of the repo! wooooot!
